### ISSUE TITLE
2x15 Spawn Point Shows on Map as 45mins, in Reality is 15mins

### ISSUE THREAD

**Issue by c00ni** [seikur0/PGO-mapscan-opt#103] opened 2016-08-17 05:55 UTC
This is the second time we've experienced driving to a spawn and it not being there, but this time I was able to fetch very specific info as it was a rare spawn.

Spawn point in question from the optimisation file:

```
  {
   "pausetime": 15,
   "spawntime": 38.932866666466,
   "pauses": 2,
   "lat": -33.785360956106814,
   "lng": 151.08375638786157,
   "phasetime": 60,
   "type": 201,
   "id": 7357988011497
  }
```

As expected, there are two entries for Blastoise at SpawnID 7357988011497 (-33.7853609561, 151.083756388) in my spawns.txt file:
spawnTime 1471408735.97 (Wed, 17 Aug 2016 04:38:55 GMT)
Time 1471408749.26 (Wed, 17 Aug 2016 04:39:09 GMT)
and
spawnTime 1471410535.97 (Wed, 17 Aug 2016 05:08:55 GMT)
Time 1471410549.26 (Wed, 17 Aug 2016 05:09:09 GMT)

He appeared after my mates and I had parted ways so we drove to it separately with different timings. Here is the timeline - I've converted our times to GMT.
04:39 GMT: Pushbullet sent a notification of the Blastoise. I've modified my message to show `str(int(mod_tth / 1000.0 / 60.0))` so it shows minutes remaining. It said 14 minutes.
04:47 GMT: I went and caught this Blastoise. It has good moves so I look at the map and it says **35min** remaining and I text this information to them.
04:59 GMT: Friend informs me it's not appearing in game.
05:00 GMT: Friend sends a screenshot of the map showing 23m remaining on Blastoise, and a pin of his location right on top.

So, there was Blastoise at this 2x15 spawn point that despawned after 15 minutes and was displayed on the map as 45 minutes.

**Comment by seikur0** [comment] 2016-08-17 06:14
Then it is an older version of the map, the newer one, wouldn't have shown '23 m remaining' but '8 m hidden' and after that time '15 min remaining' instead. (I went out yesterday and saw this in some occasions, working as intended.) (But maybe I should change the text color to grey or something.)

I think I know what the issue was for that time before as well. In a 2x15min spawn you can only catch the pokemon once, even though it'll apear twice. If you caught it during the first 15 minutes, it also won't appear on your nearby list in the second 15 minutes.

**Comment by c00ni** [comment] 2016-08-17 06:17
No no, I never caught it before.
Hmmm, am I using an outdated index.html or main0.py? I thought the only mod I did to main0 was the notification text... I guess I'll re-clone the lot.

Wait so how does 2x15 work? 15 mins on, 15 off then 15 on again? - but the same actual pokemon so you can't catch it twice...

**Comment by seikur0** [comment] 2016-08-17 06:20
Yes, that's how 2x15min works. It's like 1x45min with the pokemon being hidden between 15 m and 30 m.

**Comment by c00ni** [comment] 2016-08-17 06:28
Hmmm I'll double check my files and reopen if it happens again.
Cheers.

**Comment by c00ni** [comment] 2016-08-17 11:25
I just checked, my main0.py is up to date (with the only lines being different the pushbullet stuff) and my index.html has all the `timehiddentext = "Hidden for: ";` stuff - so also up to date?

**Comment by seikur0** [comment] 2016-08-17 11:34
Do you also have the
'DATA.append([wild.pokemon_data.pokemon_id, spawnIDint, wild.latitude, wild.longitude, int((wild.last_modified_timestamp_ms + mod_tth + 1800000) / 1000.0),addinfo])' as well with the 1800000, that you fixed? ^^ When I tested it yesterday it worked flawlessly, I even mistakenly went to some spawns, that were hidden and they were of course not there. I waited and they spawned at the expected time shown by the map.

**Comment by c00ni** [comment] 2016-08-17 12:11
Just trying to trace the flow of data to the map's marker text if a spawn is 2x15, tell me if I'm correct?

https://github.com/seikur0/PGO-mapscan-opt/blob/master/main0.py#L1142

```
if spawn['type'] == SPAWN_2x15 and finished_ms < 1800000:
    addinfo = 1
```

https://github.com/seikur0/PGO-mapscan-opt/blob/master/main0.py#L1156

```
if addinfo:
    DATA.append([wild.pokemon_data.pokemon_id, spawnIDint, wild.latitude, wild.longitude, int((wild.last_modified_timestamp_ms + mod_tth + 1800000) / 1000.0),addinfo])
```

So a value of 1 is passed as p[5] in index.html
https://github.com/seikur0/PGO-mapscan-opt/blob/master/webres/index.html#L89

```
if (p.length == 6)
    var newaddinfo = p[5];
```

The actual text shown on the marker doesn't contain newaddinfo, only
https://github.com/seikur0/PGO-mapscan-opt/blob/master/webres/index.html#L102
`markers[s].infotext = "<b>"+pokenames[p[0]]+"</b><br>"+ timelefttext + Math.floor(timeleft/60) + "m " + (timeleft%60) + "s";`
and newaddinfo (whose value is just 1) gets assigned to the addinfo property of markers[s]
https://github.com/seikur0/PGO-mapscan-opt/blob/master/webres/index.html#L109
`markers[s].addinfo=newaddinfo;`

So two things, looking at the Google Maps API, I can't see an addinfo property for markers and even if it did add some text, wouldn't it just display "1"?

**Comment by seikur0** [comment] 2016-08-17 12:14
What about these lines here:

```
                        var hidden = false
                        if (markers[i].addinfo == 1){
                            if (timeleft > 1800) {
                                timeleft -= 1800;
                            }else if ( timeleft > 900) {
                                timeleft -= 900;
                                var hidden = true
                            }
                        }
                        if (hidden)
                            markers[i].infotext= "<b>"+pokenames[markers[i].id]+"</b><br>"+ timehiddentext + Math.floor(timeleft/60) + "m " + (timeleft%60) + "s";
                        else
                            markers[i].infotext= "<b>"+pokenames[markers[i].id]+"</b><br>"+ timelefttext + Math.floor(timeleft/60) + "m " + (timeleft%60) + "s";
```

**Comment by seikur0** [comment] 2016-08-17 12:15
You can btw add arbitrary properties to the markers just as I do with validTill and id.

**Comment by c00ni** [comment] 2016-08-17 12:24
Oh man I'm a goose. I was only searching for newaddinfo and missed that entire block of code.

Ok, I'm still left baffled at this though:
http://i.imgur.com/nWEKLI3.jpg
(We are GMT+10 so the screenshot was taken at 05:00 GMT)

**Comment by seikur0** [comment] 2016-08-17 12:27
Looks pretty badass :D

**Comment by c00ni** [comment] 2016-08-17 12:29
(As in why it's not showing "Hidden for:" instead.)
He was indeed a badass, 1626CP with Water Gun and Hydro Pump!

**Comment by seikur0** [comment] 2016-08-17 12:31
I'd guess it was before your  Missing 0 (#102)  fix?

Wow.. Probably still very bad IV though xD

**Comment by c00ni** [comment] 2016-08-17 12:40
Haven't checked yet... but yes, probably terrible

The main0_old.py (which I renamed before downloading a new copy from the repo and making changes after I got home from the afternoon's hunt) that was the one running at 3pm has a last modified time of 8:33am this morning and contains the missing 0 fix =/

Of course the bug is on a very rare spawn type making it almost impossible to test

**Comment by seikur0** [comment] 2016-08-17 12:51
Not that rare, you do have 80 of them. I don't know, if you notice something like that again, let me know.

**Comment by c00ni** [comment] 2016-08-17 12:54
Just realised you can easily manually spot them in the data file.
Will reopen (again) if I can show it acting as a 1x45 again.

**Comment by seikur0** [comment] 2016-08-17 12:56
Okay.

**Comment by c00ni** [comment] 2016-08-17 14:06
I saw it on the map showing 35 minutes left, then go down past 30 minutes and continue to show on the map.

From data0.json
`[58,7357990364113,-33.77100727166748,151.10960093664235,1471443832,1]`

From spawn point file

```
  {
   "pausetime": 15,
   "spawntime": 38.875800002366304,
   "pauses": 2,
   "lat": -33.77100727166748,
   "lng": 151.10960093664235,
   "phasetime": 60,
   "type": 201,
   "id": 7357990364113
  }
```

From spawns0.txt

```
Growlithe   58  7357990364113   -33.7710072717  151.109600937   1471441132.55   1471441139.73   892.82  378508388559388957
Growlithe   58  7357990364113   -33.7710072717  151.109600937   1471442932.55   1471442939.73   892.82  378508388559388957
```

And the screenshot:
http://i.imgur.com/HvKYbUi.jpg

**Comment by seikur0** [comment] 2016-08-17 14:16
The data is looking good. Could this actually be a "you need to clear your cache" issue?

**Comment by c00ni** [comment] 2016-08-18 02:32
Finally found the problem. I don't get how it was working on your map? Unless you didn't push the version you're using.

The marker's timeleft and timelefttext/timehiddentext were being updated on live markers and _afterwards_ all the values were being overridden by raw data from the data file.

**Comment by seikur0** [comment] 2016-08-18 07:19
Okay, I don't get how it was working on my map either haha The mysteries of programming.. Fixed now.

**Closed as completed by seikur0** 2016-08-18 07:19 UTC
