### ISSUE TITLE
No JSON object could be decoded

### ISSUE THREAD

**Issue by furier** [seikur0/PGO-mapscan-opt#212] opened 2016-09-17 14:05 UTC
This exception sometimes occurre after restarting `main0.py` and it in the authorization phase i think...

```
Exception in thread Thread-16:
Traceback (most recent call last):
  File "/opt/local/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/home/sander/PGO-mapscan-opt/main0.py", line 1250, in run
    do_login(self.account)
  File "/home/sander/PGO-mapscan-opt/main0.py", line 484, in do_login
    login_ptc(account)
  File "/home/sander/PGO-mapscan-opt/main0.py", line 455, in login_ptc
    answer = json.loads(r.content)
  File "/opt/local/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/opt/local/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/opt/local/lib/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
```

**Comment by seikur0** [comment] 2016-09-17 20:42
duplicate of #210

**Closed as completed by seikur0** 2016-09-17 20:42 UTC
