### ISSUE TITLE
"IndexError: list index out of range" main0.py, line 815

### ISSUE THREAD

**Issue by Trustmania** [seikur0/PGO-mapscan-opt#164] opened 2016-09-10 13:04 UTC
`[+] 13238 of 67951 cells detected as empty during last run.
[+] Non-empty heartbeats reached a maximum of 1 retries, allowed: 1.
[+] Average number of retries was 0.0, total number 78.
[+] 12182 locations were permanently removed as empty. They've been empty during 2 consecutive scans covering a time of 7200 seconds.
Scandata was written to file.

[+] Starting intelligent scan mode.

[+] Spawn point count: 8344
[+] Type: 1x15, Count: 0, Percentage: 0.0%
[+] Type: 1x30, Count: 0, Percentage: 0.0%
[+] Type: 1x45, Count: 0, Percentage: 0.0%
[+] Type: 1x60, Count: 0, Percentage: 0.0%
[+] Type: 2x15, Count: 0, Percentage: 0.0%
[+] Type: 1x60h2, Count: 0, Percentage: 0.0%
[+] Type: 1x60h3, Count: 0, Percentage: 0.0%
[+] Type: 1x60h23, Count: 0, Percentage: 0.0%
[+] Type: UNDEF/DEF, Count: 8344, Percentage: 100.0%

Exception in thread Thread-49:
Traceback (most recent call last):
  File "C:\Python27\lib\threading.py", line 530, in __bootstrap_inner
    self.run()
  File "F:/development/git/sbi/PGO-mapscan-opt/main0.py", line 815, in run
    if curT <= all_sort[pointnum-1][0]:
IndexError: list index out of range`

**Comment by seikur0** [comment] 2016-09-10 13:20
and another duplicate of #146

closed

**Closed as completed by seikur0** 2016-09-10 13:20 UTC
