### ISSUE TITLE
[crash] when itelligent scan starts

### ISSUE THREAD

**Issue by dikkedeur** [seikur0/PGO-mapscan-opt#161] opened 2016-09-10 05:55 UTC
When the intelligent start scan starts it trows out this error

[+] Starting intelligent scan mode.

[+] Spawn point count: 1151
[+] Type: 1x15, Count: 0, Percentage: 0.0%
[+] Type: 1x30, Count: 0, Percentage: 0.0%
[+] Type: 1x45, Count: 0, Percentage: 0.0%
[+] Type: 1x60, Count: 0, Percentage: 0.0%
[+] Type: 2x15, Count: 0, Percentage: 0.0%
[+] Type: 1x60h2, Count: 0, Percentage: 0.0%
[+] Type: 1x60h3, Count: 0, Percentage: 0.0%
[+] Type: 1x60h23, Count: 0, Percentage: 0.0%
[+] Type: UNDEF/DEF, Count: 1151, Percentage: 100.0%

Exception in thread Thread-46:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "main0.py", line 921, in run
    if curT <= all_sort[pointnum-1][0]:
IndexError: list index out of range

running on ubuntu 16.04 lte
with 40 accounts.

**Comment by seikur0** [comment] 2016-09-10 08:12
duplicate of https://github.com/seikur0/PGO-mapscan-opt/issues/146

closed

**Closed as completed by seikur0** 2016-09-10 08:12 UTC

**Comment by dikkedeur** [comment] 2016-09-10 08:31
sidenote: what fixed for me was reducing the scanradius from 50 to 30
